### ISSUE TITLE
Win10 IE with Selenium and IEDriver 3.11.0 fails

### ISSUE THREAD

**Issue by dhoer** [agabrys/chocolatey-packages#19]
I tried running IE tests with Selenium and IEDriver 3.11.0 on Windows 10 in vagrant https://github.com/dhoer/choco-selenium/blob/master/Vagrantfile and get the following error:

```
Internet Explorer
  should Google Search for Cheese! (FAILED - 1)

An error occurred in an `after(:context)` hook.
On host `localhost'
Failure/Error: @driver.quit
NoMethodError:
  undefined method `quit' for nil:NilClass

# ./spec/localhost/zie_spec.rb:11:in `block (2 levels) in <top (required)>'

Failures:

  1) Internet Explorer should Google Search for Cheese!
     On host `localhost'
     Failure/Error: @driver = Selenium::WebDriver.for(:remote, url: "http://localhost:4446/wd/hub", desired_capabilities: :ie)
     Selenium::WebDriver::Error::SessionNotCreatedError:
       Unable to create session from org.openqa.selenium.remote.NewSessionPayload@36958aee
       Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:33:15.31Z'
       System info: host: 'VAGRANT-10', ip: '10.0.2.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_162'
       Driver info: driver.version: unknown

     # [remote server] org.openqa.selenium.remote.server.NewSessionPipeline(NewSessionPipeline.java):75:in `lambda$null$4'
     # [remote server] java.util.Optional(Optional.java):290:in `orElseThrow'
     # [remote server] org.openqa.selenium.remote.server.NewSessionPipeline(NewSessionPipeline.java):74:in `lambda$createNewSession$5'
     # [remote server] java.util.Optional(Optional.java):267:in `orElseGet'
     # [remote server] org.openqa.selenium.remote.server.NewSessionPipeline(NewSessionPipeline.java):72:in `createNewSession'
     # [remote server] org.openqa.selenium.remote.server.commandhandler.BeginSession(BeginSession.java):65:in `execute'
     # [remote server] org.openqa.selenium.remote.server.WebDriverServlet(WebDriverServlet.java):246:in `lambda$handle$1'
     # [remote server] java.util.concurrent.Executors$RunnableAdapter(Executors.java):511:in `call'
     # [remote server] java.util.concurrent.FutureTask(FutureTask.java):266:in `run'
     # [remote server] java.util.concurrent.ThreadPoolExecutor(ThreadPoolExecutor.java):1149:in `runWorker'
     # [remote server] java.util.concurrent.ThreadPoolExecutor$Worker(ThreadPoolExecutor.java):624:in `run'
     # [remote server] java.lang.Thread(Thread.java):748:in `run'
     # ./spec/localhost/zie_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 39.17 seconds (files took 2.11 seconds to load)
19 examples, 1 failure, 1 error occurred outside of examples

Failed examples:

rspec ./spec/localhost/zie_spec.rb:14 # Internet Explorer should Google Search for Cheese!

C:/tools/ruby24/bin/ruby.exe -I'C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/rspec-support-3.7.1/lib';'C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib' 'C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/exe/rspec' --pattern 'spec/localhost/*_spec.rb' failed
```

I haven't changed anything as far as unit test go.  Do you have any idea why this is no longer working? I'm stumped.

**Comment by dhoer** [comment]
Log output from node:

```
13:36:00.748 INFO [ActiveSessionFactory.apply] - Capabilities are: Capabilities {browserName: internet explorer, cssSelectorsEnabled: true, javascriptEnabled: false, nativeEvents: true, platform: WINDOWS, rotatable: false, takesScreenshot: true, version: }
13:36:00.748 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.ie.InternetExplorerDriverService)
Started InternetExplorerDriver server (64-bit)
3.11.0.0
Listening on port 20230
Only local connections are allowed
13:36:05.405 WARN [RemoteSession$Factory.performHandshake] - Failed to connect to localhost/0:0:0:0:0:0:0:1:20230
java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:20230
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:101)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.server.RemoteSession$Factory.performHandshake(RemoteSession.java:145)
	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:159)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$apply$12(ActiveSessionFactory.java:176)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.apply(ActiveSessionFactory.java:179)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$null$2(NewSessionPipeline.java:65)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.server.NewSessionPipeline.lambda$createNewSession$3(NewSessionPipeline.java:68)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.Streams$StreamBuilderImpl.tryAdvance(Streams.java:405)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.server.NewSessionPipeline.createNewSession(NewSessionPipeline.java:71)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:65)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$1(WebDriverServlet.java:246)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	... 71 more
```

**Comment by dhoer** [comment]
The 3.11.1 release should fix this issue https://github.com/SeleniumHQ/selenium/issues/5519.

v3.11.1.0
=========
 * Updated all C++ projects for the IE driver to use the Windows 8.1 SDK.
   This has the unfortunate side effect that the driver executable will no
   longer launch on Windows XP.
 * Removed direct call to InternetGetCookieEx2 API. Versions of IE prior to
   11 do not have access to this API. Linking directly to it via the Windows
   8.1 SDK creates an import entry in the IEDriver.dll library used by the
   driver. So that the driver can continue to be used against earlier releases,
   we will call the API using GetModuleHandle and GetProcAddress only if it
   exists in the version of WinINet being used by the browser. Fixes issue #5603.
 * **Properly initializing JSON values in IE driver. Fixes issue #5519.**

**Comment by dhoer** [comment]
@ajjl

**Comment by agabrys** [comment]
Done: https://chocolatey.org/packages/selenium-ie-driver/3.11.1

**Comment by dhoer** [comment]
Awesome! Thanks
